Shopping/Controllers/CartController.cs
using System.Diagnostics;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Shopping.Models;

namespace Shopping.Controllers;

public class CartController : Controller
{
   
    private ConnectDB db;
    public CartController(IConfiguration cfg)
    {
        db = new ConnectDB(cfg.GetConnectionString("connection"));
    }


    public IActionResult Index()
    {
        //check if sessionid exists in cookies.
        if (Request.Cookies["SessionId"] != null)
        {
            ViewData["username"] = db.GetUserBySession(Request.Cookies["SessionId"]).Username;
            ViewBag.Cookies = Request.Cookies["SessionId"];
        }

        string productids = "";


        if (Request.Cookies["items"] != null)
        {
            productids = Request.Cookies["items"];
        }

        ViewData["products"] = db.RetrieveProduct(productids);
        return View();
    }

}

Shopping/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shopping;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Shopping.Controllers
{
    public class LoginController : Controller
    {

        private ConnectDB db;

        public LoginController(IConfiguration cfg)
        {
            db = new ConnectDB(cfg.GetConnectionString("connection"));
        }


        public IActionResult isLogin(string returnURL)
        {
            if (Request.Cookies["SessionId"] != null)
            {
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Index", new RouteValueDictionary(new { controller = "Login", Action = "Index", returnURL = returnURL }));

        }


        //[HttpPost]
        public IActionResult Index(string username, string password, string returnURL)
        {
            User user = db.GetUserByUsername(username);
            if (user != null)
            {

                if (user.Password == password)
                {

                    string sessionId = db.AddSession(user.UserId);

                    CookieOptions options = new CookieOptions();
                    options.Expires = DateTime.Now.AddDays(1);
                    Response.Cookies.Append("SessionId", sessionId, options);

                    if (!string.IsNullOrEmpty(returnURL))
                    {
                        return Redirect(returnURL);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }

                }
                else
                {
                    ViewBag.loginErr = "Your Username or Password is incorrect. Please try again.";
                }
            }

            if (username != null)
            {
                ViewBag.loginErr = "Your Username or Password is incorrect. Please try again.";
            }


            ViewBag.param = returnURL;
            return View();
        }


    }
}

Shopping/Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shopping;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ShoppingWebsite.Controllers
{
    public class LogoutController : Controller
    {
        private ConnectDB db;

        public LogoutController(IConfiguration cfg)
        {
            db = new ConnectDB(cfg.GetConnectionString("connection"));
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            if (Request.Cookies["SessionId"] != null)
            {
                // remove our entry from database
                db.RemoveSession(Request.Cookies["SessionId"]);

                // ask client to remove its cookie so that it won't sent
                // it back next time
                Response.Cookies.Delete("SessionId");
                Response.Cookies.Delete("items");

            }

            return RedirectToAction("Index", "Login");
        }
    }
}

Shopping/Controllers/PurchaseListController.cs
using System.Diagnostics;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Shopping.Models;

namespace Shopping.Controllers;

public class PurchaseListController : Controller
{
    private ConnectDB db;
    public PurchaseListController(IConfiguration cfg)
    {
        db = new ConnectDB(cfg.GetConnectionString("connection"));
    }

    public IActionResult Index()
    {
        if (Request.Cookies["SessionId"] == null)
        {
            return RedirectToAction("Index", "Login");
        }
        User user = db.GetUserBySession(Request.Cookies["SessionId"]);
        int userId = user.UserId;

    
            List<PurchasedList> products = db.RetrievePurchase(userId);
            ViewData["pruchaseList"] = products;
            List<PurchasedActivation> activities = db.RetrieveActivations(userId);
            ViewData["activities"] = activities;
            ViewData["username"] = user.Username;
       
        return View();
    }


    public IActionResult GetStar()
    {
        User user = db.GetUserBySession(Request.Cookies["SessionId"]);
        int userId = user.UserId;
        List<Reviews> nodes = db.GetStar(userId);
        return Content(JsonSerializer.Serialize(nodes));
    }


    public string SetStarRating(int productId, int rating)
    {
        User user = db.GetUserBySession(Request.Cookies["SessionId"]);
        int userId = user.UserId;
        List<Reviews> nodes = db.GetStar(userId);
        bool status = db.RatingIsExist(userId, productId, rating);

        return status ? "success" : "fail";
    }
  
}

Shopping/Views/Shared/_Alogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/Shopping.styles.css" />
    <script src="https://kit.fontawesome.com/a103fe44a3.js" crossorigin="anonymous"></script>

</head>

<body>

    <header>
        <nav class="navbar navbar-expand-sm fixed-top navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container-fluid container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hello, @ViewData["Username"]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PurchaseList" asp-action="Index">My Purchases</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" onclick="clearLocal()" asp-area="" asp-controller="Logout" asp-action="Index">Logout</a>
                        </li>
                    </ul>

                    <form class="d-flex" action="/Home/Cart/" method="POST">
                        <button class="btn btn-outline-dark" id="cartbtn" asp-controller="Cart" asp-action="Index" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge text-white ms-1 rounded-pill spanc" id="totalNum">0</span>
                        </button>
                    </form>

                </div>
            </div>
        </nav>
    </header>


    <div class="container notmain">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <p class="text-center dfooter">Copyright &copy; Team#3.com</p>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script>
        function clearLocal() {
            localStorage.clear();
        }
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shopping/Views/Shared/_Blogincart.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/Shopping.styles.css" />
    <script src="https://kit.fontawesome.com/a103fe44a3.js" crossorigin="anonymous"></script>

</head>

<body>

    <header>
        <nav class="navbar navbar-expand-sm fixed-top navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hello, Guest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <form class="bloginform" action="/Login/isLogin" method="get">
                                <input type="hidden" value="/Cart" name="returnURL" />
                                <button class="btn" type="submit">Login</button>
                            </form>
                        </li>
                    </ul>

                    <form class="d-flex" action="/Cart/" method="POST">
                        <button class="btn btn-outline-dark" id="cartbtn" asp-controller="Cart" asp-action="Index" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge text-white ms-1 rounded-pill spanc" id="totalNum">0</span>
                        </button>
                    </form>

                </div>
            </div>
        </nav>
    </header>


    <div class="container notmain">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <p class="text-center dfooter">Copyright &copy; Team#3.com</p>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
     
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shopping/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/Shopping.styles.css" />
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-sm fixed-top navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container-fluid container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hello, Guest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                    </ul>

                    <form class="d-flex" action="/Cart/" method="POST">
                        <button class="btn btn-outline-dark" id="cartbtn" asp-controller="Cart" asp-action="Index" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge text-white ms-1 rounded-pill spanc" id="totalNum">0</span>
                        </button>
                    </form>

                </div>
            </div>
        </nav>
    </header>


    <div class="container notmain">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <p class="text-center dfooter">Copyright &copy; Team#3.com</p>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shopping/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Login</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
   
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/login.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shopping/Views/Shared/_PurchaseList.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shopping.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/a103fe44a3.js" crossorigin="anonymous"></script>
   
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm fixed-top navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hello, @ViewData["Username"]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                        
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Index">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container notmain">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <p class="text-center dfooter">Copyright &copy; Team#3.com</p>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/purchaselist.js"></script>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>